// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReactRouter = require("reason-react/src/ReasonReactRouter.js");
var Home$AccessibilityDojo = require("./Home.bs.js");
var Failed$AccessibilityDojo = require("./Failed.bs.js");
var Footer$AccessibilityDojo = require("./Footer.bs.js");
var Header$AccessibilityDojo = require("./Header.bs.js");
var Success$AccessibilityDojo = require("./Success.bs.js");
var Conference$AccessibilityDojo = require("./Conference.bs.js");

function isFormFilledOut(searchPath) {
  return searchPath.split("=").length >= 10;
}

function App(Props) {
  var url = ReasonReactRouter.useUrl(undefined, /* () */0);
  var match = url[/* path */0];
  var tmp;
  if (match) {
    if (match[0] === "conf") {
      var searchPath = url[/* search */2];
      tmp = searchPath.length === 0 ? React.createElement(React.Fragment, undefined, React.createElement("div", {
                  className: "container2"
                }), React.createElement(Conference$AccessibilityDojo.make, { })) : (
          isFormFilledOut(searchPath) ? React.createElement(Success$AccessibilityDojo.make, { }) : React.createElement(Failed$AccessibilityDojo.make, { })
        );
    } else {
      tmp = React.createElement(Home$AccessibilityDojo.make, { });
    }
  } else {
    tmp = React.createElement(Home$AccessibilityDojo.make, { });
  }
  return React.createElement(React.Fragment, undefined, React.createElement(Header$AccessibilityDojo.make, { }), tmp, React.createElement(Footer$AccessibilityDojo.make, { }));
}

var make = App;

exports.isFormFilledOut = isFormFilledOut;
exports.make = make;
/* react Not a pure module */
