// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

(( require('./conf.css') ));

function Conference(Props) {
  return React.createElement("div", {
              className: "main-conf"
            }, React.createElement("div", {
                  className: "card"
                }, React.createElement("form", undefined, React.createElement("div", {
                          className: "container"
                        }, React.createElement("h2", undefined, "Accessibility Haters 2019"), React.createElement("div", {
                              className: "trip-selector"
                            }, React.createElement("label", undefined, React.createElement("input", {
                                      name: "tType",
                                      type: "radio",
                                      value: "0"
                                    }), " One Ticket"), React.createElement("label", undefined, React.createElement("input", {
                                      name: "tType",
                                      type: "radio",
                                      value: "1"
                                    }), " Two Tickets"), React.createElement("label", undefined, React.createElement("input", {
                                      name: "tType",
                                      type: "radio",
                                      value: "2"
                                    }), " More Tickets")), React.createElement("div", {
                              className: "row"
                            }, React.createElement("label", {
                                  htmlFor: "fName"
                                }, "Full Name"), React.createElement("input", {
                                  id: "fName",
                                  name: "fName",
                                  type: "text"
                                })), React.createElement("div", {
                              className: "row"
                            }, React.createElement("label", {
                                  htmlFor: "address"
                                }, "Enter your address"), React.createElement("textarea", {
                                  id: "address",
                                  name: "addressTxt"
                                })), React.createElement("div", {
                              className: "row"
                            }, React.createElement("div", {
                                  className: "inline-control col-1"
                                }, React.createElement("label", {
                                      htmlFor: "seatType"
                                    }, "Seat Type"), React.createElement("input", {
                                      id: "seatType",
                                      list: "seatTypes",
                                      name: "seatType",
                                      type: "text"
                                    }), React.createElement("datalist", {
                                      id: "seatTypes"
                                    }, React.createElement("option", {
                                          value: "Amazing"
                                        }), React.createElement("option", {
                                          value: "Meh"
                                        }), React.createElement("option", {
                                          value: "Ouch after like 30 minutes"
                                        }), React.createElement("option", {
                                          value: "The back killer"
                                        }), React.createElement("option", {
                                          value: "There might be a nail in the middle of my seat"
                                        }))), React.createElement("div", {
                                  className: "inline-control col-1"
                                }, React.createElement("label", {
                                      htmlFor: "annoying"
                                    }, "What annoys you?"), React.createElement("input", {
                                      id: "annoying",
                                      list: "annoyingList",
                                      name: "annoying",
                                      type: "text"
                                    }), React.createElement("datalist", {
                                      id: "annoyingList"
                                    }, React.createElement("option", {
                                          value: "Accessibility"
                                        }), React.createElement("option", {
                                          value: "Accessibility"
                                        }), React.createElement("option", {
                                          value: "Accessibility"
                                        }), React.createElement("option", {
                                          value: "Accessibility"
                                        }), React.createElement("option", {
                                          value: "Accessibility"
                                        }))), React.createElement("div", {
                                  className: "inline-control col-1"
                                }, React.createElement("label", {
                                      htmlFor: "dDate"
                                    }, "Arrival Date"), React.createElement("input", {
                                      id: "dDate",
                                      name: "dDate",
                                      type: "date"
                                    })), React.createElement("div", {
                                  className: "inline-control col-1"
                                }, React.createElement("label", {
                                      htmlFor: "rDate"
                                    }, "First Hate Date"), React.createElement("input", {
                                      id: "rDate",
                                      name: "rDate",
                                      type: "date"
                                    }))), React.createElement("div", {
                              className: "row"
                            }, React.createElement("div", {
                                  className: "inline-control col-2"
                                }, React.createElement("label", {
                                      htmlFor: "at"
                                    }, "Least favourite assistive technology"), React.createElement("select", {
                                      id: "at",
                                      name: "at"
                                    }, React.createElement("option", {
                                          value: "0"
                                        }, "Screen readers"), React.createElement("option", {
                                          value: "1"
                                        }, "Voice recognition"), React.createElement("option", {
                                          value: "2"
                                        }, "Automatic page turners"))), React.createElement("div", {
                                  className: "inline-control sign-up col-1"
                                }, React.createElement("label", undefined, React.createElement("input", {
                                          name: "jLetter",
                                          type: "checkbox"
                                        }), " Bringing a pet?")), React.createElement("div", {
                                  className: "inline-control submit-form col-1"
                                }, React.createElement("button", {
                                      id: "submitBtn",
                                      type: "submit"
                                    }, "Buy")))))));
}

var make = Conference;

exports.make = make;
/*  Not a pure module */
