// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

(( require('./failed.css') ));

function Failed(Props) {
  return React.createElement("div", {
              className: "img-failed"
            });
}

var make = Failed;

exports.make = make;
/*  Not a pure module */
