// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Footer(Props) {
  return React.createElement("footer", {
              className: "footer"
            }, React.createElement("nav", {
                  className: "col-4"
                }, React.createElement("a", {
                      className: "navBarItem",
                      href: "/"
                    }, String.fromCharCode(169) + " Accessibility Haters")));
}

var make = Footer;

exports.make = make;
/* react Not a pure module */
