// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Header(Props) {
  return React.createElement("header", {
              className: "header"
            }, React.createElement("nav", undefined, React.createElement("a", {
                      className: "navBarItem",
                      href: "/"
                    }, React.createElement("div", {
                          className: "logoText"
                        }, "Accessibility ", React.createElement("span", {
                              className: "logoText2"
                            }, "Haters"))), React.createElement("a", {
                      className: "navBarItem",
                      href: "/conf"
                    }, "AccHaters Conf 2019!"), React.createElement("a", {
                      className: "navBarItem",
                      href: "/"
                    }, "About us")));
}

var make = Header;

exports.make = make;
/* react Not a pure module */
