// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

(( require('./home.css') ));

function Home(Props) {
  return React.createElement("div", {
              className: "main"
            }, React.createElement("div", {
                  className: "home-container"
                }, React.createElement("div", {
                      className: "offscreen"
                    }, "Top story"), React.createElement("div", {
                      className: "article"
                    }, React.createElement("div", {
                          className: "main-story"
                        }, React.createElement("img", {
                              className: "pull-right",
                              alt: "Arena with conf guests",
                              src: "https://bit.ly/2kuIbh3"
                            }), React.createElement("div", {
                              className: "info"
                            }, React.createElement("div", {
                                  className: "headline"
                                }, "Accessibility Haters Conf 2019!"), React.createElement("p", undefined, "It's already been a year and boy are we excited to announce the 2019 Accessibility Haters Conference!\n               Last year 50.000 extremely angry people came together and experienced probably the biggest hate conference in the world!\n               This year we're aiming for bigger and darker things, as we're moving to break the last 50k entry!\n               To make that happen we're going to offer early bird tickets for a random amount, so just enter your credit card info and you might get lucky!\n               ", React.createElement("a", {
                                      href: "conf"
                                    }, "Get your early bird tickets here!"))))), React.createElement("div", {
                      className: "side-by-side"
                    }, React.createElement("div", {
                          className: "column"
                        }, React.createElement("div", {
                              className: "tier-header"
                            }, React.createElement("div", undefined, "In the news")), React.createElement("div", {
                              className: "article"
                            }, React.createElement("div", {
                                  className: "headline"
                                }, "Study shows dyslexia is FAKE NEWS!!!!! ", React.createElement("a", {
                                      href: "https://www.dyslexicadvantage.org/fake-news/"
                                    }, "Read More About Fake News on Dyslexia")), React.createElement("img", {
                                  className: "img-news",
                                  alt: "fake news",
                                  src: "https://bit.ly/2kuIPet"
                                }))), React.createElement("div", {
                          className: "column"
                        }, React.createElement("div", {
                              className: "article"
                            }, React.createElement("div", undefined, React.createElement("img", {
                                      alt: "color blindness test dots",
                                      src: "https://bit.ly/2kaN4vi"
                                    }), React.createElement("div", {
                                      className: "info"
                                    }, React.createElement("div", {
                                          className: "headline"
                                        }, "Color blindness is a lie!"), React.createElement("p", undefined, "Researchers say that it's actually impossible to see how people see colors. ", React.createElement("a", {
                                              href: "https://www.color-blindness.com/2007/07/05/pretending-color-blindness-how-to-uncover-it/"
                                            }, "Read more on color blindness"))))))), React.createElement("div", {
                      className: "three-col"
                    }, React.createElement("div", {
                          className: "tier-header"
                        }, React.createElement("div", undefined, "Recommended")), React.createElement("div", {
                          className: "columns"
                        }, React.createElement("div", {
                              className: "article"
                            }, React.createElement("img", {
                                  className: "img-recommended",
                                  alt: "grimacing man holding ears",
                                  src: "https://bit.ly/2lM98gp"
                                }), React.createElement("div", {
                                  className: "info"
                                }, React.createElement("div", {
                                      className: "headline"
                                    }, "VoiceOver proven to cause extreme headaches and nausea ", React.createElement("a", {
                                          href: "https://www.webmd.com/migraines-headaches/migraines-headaches-basics#1"
                                        }, "Read more on VoiceOver causing headaches")))), React.createElement("div", {
                              className: "article"
                            }, React.createElement("img", {
                                  className: "img-recommended",
                                  alt: "LOL",
                                  src: "https://bit.ly/2lKUoOI"
                                }), React.createElement("div", {
                                  className: "info"
                                }, React.createElement("div", {
                                      className: "headline"
                                    }, "The newest fad in the accessibility world is something called a screen reader. ", React.createElement("a", {
                                          href: "https://en.wikipedia.org/wiki/Screen_reader"
                                        }, "Read More")))), React.createElement("div", {
                              className: "article"
                            }, React.createElement("img", {
                                  className: "img-recommended",
                                  alt: "content not available",
                                  src: "https://bit.ly/2kHTNgr"
                                }), React.createElement("div", {
                                  className: "info"
                                }, React.createElement("div", {
                                      className: "headline"
                                    }, "Location, location, location! It's not our fault you are in the wrong place! ", React.createElement("a", {
                                          href: "https://en.wikipedia.org/wiki/Location"
                                        }, "Read More about location"))))))));
}

var make = Home;

exports.make = make;
/*  Not a pure module */
