// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var App$AccessibilityDojo = require("./App.bs.js");

(( require('./reset.css') ));

(( require('./app.css') ));

(( require('./header.css') ));

ReactDOMRe.renderToElementWithId(React.createElement(App$AccessibilityDojo.make, { }), "index");

/*  Not a pure module */
