// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

(( require('./success.css') ));

function Success(Props) {
  return React.createElement("div", {
              className: "img-success"
            });
}

var make = Success;

exports.make = make;
/*  Not a pure module */
