// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

(( require('./success.css') ));

function Success(Props) {
  return React.createElement("img", {
              className: "img-success",
              alt: "success med s\xc3\xb8d hund",
              src: "https://i.imgflip.com/3acpdu.jpg"
            });
}

var make = Success;

exports.make = make;
/*  Not a pure module */
